# Generated by Django 5.0.2 on 2024-02-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="slud",
            new_name="slug",
        ),
        migrations.AlterField(
            model_name="property",
            name="photo1",
            field=models.ImageField(
                blank=True,
                default="/interior_sample.jpg",
                null=True,
                upload_to="",
                verbose_name="Photo1",
            ),
        ),
    ]
